/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.Font;

/**
 *
 * @author Cross
 */
public class MainScreen extends javax.swing.JFrame {

    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        initComponents();
        decorateTableTasks();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        taskDefaultIcon = new javax.swing.JLabel();
        taskEmpty = new javax.swing.JPanel();
        taskDefaultTitle = new javax.swing.JLabel();
        taskDefaultSubtitle = new javax.swing.JLabel();
        taskEmptyPanel = new javax.swing.JPanel();
        taskEmptyIcon = new javax.swing.JLabel();
        taskEmptyTitle = new javax.swing.JLabel();
        taskEmptySubtitle = new javax.swing.JLabel();
        toolBar = new javax.swing.JPanel();
        toolBarTitle = new javax.swing.JLabel();
        toolBarSubtitle = new javax.swing.JLabel();
        mainBody = new javax.swing.JPanel();
        projects = new javax.swing.JPanel();
        projectTitle = new javax.swing.JLabel();
        projectIcon = new javax.swing.JLabel();
        tasks = new javax.swing.JPanel();
        taskTitle = new javax.swing.JLabel();
        taskIcon = new javax.swing.JLabel();
        projectItems = new javax.swing.JPanel();
        scrollProjectPanel = new javax.swing.JScrollPane();
        projectList = new javax.swing.JList<>();
        taskItems = new javax.swing.JPanel();
        scrollTablePanel = new javax.swing.JScrollPane();
        tasksTable = new javax.swing.JTable();

        taskDefaultIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskDefaultIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        taskEmpty.setBackground(new java.awt.Color(255, 255, 255));
        taskEmpty.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taskDefaultTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taskDefaultTitle.setForeground(new java.awt.Color(153, 153, 153));
        taskDefaultTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskDefaultTitle.setText("Clique no botão + para adicionar uma tarefa");

        taskDefaultSubtitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        taskDefaultSubtitle.setForeground(new java.awt.Color(0, 153, 102));
        taskDefaultSubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskDefaultSubtitle.setText("Nenhuma tarefa por aqui :D");

        javax.swing.GroupLayout taskEmptyLayout = new javax.swing.GroupLayout(taskEmpty);
        taskEmpty.setLayout(taskEmptyLayout);
        taskEmptyLayout.setHorizontalGroup(
            taskEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskEmptyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskDefaultTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                    .addComponent(taskDefaultSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        taskEmptyLayout.setVerticalGroup(
            taskEmptyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskEmptyLayout.createSequentialGroup()
                .addGap(243, 243, 243)
                .addComponent(taskDefaultSubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskDefaultTitle)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        taskEmptyPanel.setBackground(new java.awt.Color(255, 255, 255));
        taskEmptyPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taskEmptyIcon.setBackground(new java.awt.Color(255, 255, 255));
        taskEmptyIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskEmptyIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lists.png"))); // NOI18N

        taskEmptyTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        taskEmptyTitle.setForeground(new java.awt.Color(0, 153, 102));
        taskEmptyTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskEmptyTitle.setText("Nenhuma tarefa por aqui");

        taskEmptySubtitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        taskEmptySubtitle.setForeground(new java.awt.Color(153, 153, 153));
        taskEmptySubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        taskEmptySubtitle.setText("Clique no botão + para adicionar uma tarefa");

        javax.swing.GroupLayout taskEmptyPanelLayout = new javax.swing.GroupLayout(taskEmptyPanel);
        taskEmptyPanel.setLayout(taskEmptyPanelLayout);
        taskEmptyPanelLayout.setHorizontalGroup(
            taskEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskEmptyPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(taskEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(taskEmptySubtitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 588, Short.MAX_VALUE)
                    .addComponent(taskEmptyTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taskEmptyIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        taskEmptyPanelLayout.setVerticalGroup(
            taskEmptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(taskEmptyPanelLayout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(taskEmptyIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskEmptyTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(taskEmptySubtitle)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        toolBar.setBackground(new java.awt.Color(0, 153, 102));
        toolBar.setMinimumSize(new java.awt.Dimension(800, 600));

        toolBarTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        toolBarTitle.setForeground(new java.awt.Color(255, 255, 255));
        toolBarTitle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tick.png"))); // NOI18N
        toolBarTitle.setText("  Todo App");

        toolBarSubtitle.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        toolBarSubtitle.setForeground(new java.awt.Color(255, 255, 255));
        toolBarSubtitle.setText("  Anote tudo, não esqueça de nada");

        projects.setBackground(new java.awt.Color(255, 255, 255));
        projects.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        projectTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        projectTitle.setForeground(new java.awt.Color(0, 153, 102));
        projectTitle.setText("Projetos");

        projectIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        projectIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        projectIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projectIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout projectsLayout = new javax.swing.GroupLayout(projects);
        projects.setLayout(projectsLayout);
        projectsLayout.setHorizontalGroup(
            projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(projectsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(projectTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(projectIcon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        projectsLayout.setVerticalGroup(
            projectsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(projectTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(projectIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tasks.setBackground(new java.awt.Color(255, 255, 255));
        tasks.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        taskTitle.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        taskTitle.setForeground(new java.awt.Color(0, 153, 102));
        taskTitle.setText("Tarefas");

        taskIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/add.png"))); // NOI18N
        taskIcon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        taskIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                taskIconMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout tasksLayout = new javax.swing.GroupLayout(tasks);
        tasks.setLayout(tasksLayout);
        tasksLayout.setHorizontalGroup(
            tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tasksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(taskTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 458, Short.MAX_VALUE)
                .addComponent(taskIcon)
                .addContainerGap())
        );
        tasksLayout.setVerticalGroup(
            tasksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(taskIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
        );

        projectItems.setBackground(new java.awt.Color(255, 255, 255));
        projectItems.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scrollProjectPanel.setBorder(null);

        projectList.setBorder(null);
        projectList.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        projectList.setForeground(new java.awt.Color(0, 153, 102));
        projectList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { " Item 1", " Item 2", " Item 3", " Item 4", " Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        projectList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        projectList.setFixedCellHeight(50);
        projectList.setSelectionBackground(new java.awt.Color(0, 153, 102));
        projectList.setSelectionForeground(new java.awt.Color(255, 255, 255));
        scrollProjectPanel.setViewportView(projectList);
        projectList.getAccessibleContext().setAccessibleName("");
        projectList.getAccessibleContext().setAccessibleDescription("");
        projectList.getAccessibleContext().setAccessibleParent(projectList);

        javax.swing.GroupLayout projectItemsLayout = new javax.swing.GroupLayout(projectItems);
        projectItems.setLayout(projectItemsLayout);
        projectItemsLayout.setHorizontalGroup(
            projectItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollProjectPanel, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        projectItemsLayout.setVerticalGroup(
            projectItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollProjectPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        taskItems.setBackground(new java.awt.Color(255, 255, 255));
        taskItems.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        scrollTablePanel.setBorder(null);

        tasksTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tasksTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Title Descrição", "Prazo", "Status", "Editar", "Excluir"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tasksTable.setRowHeight(30);
        tasksTable.setSelectionBackground(new java.awt.Color(0, 153, 102));
        tasksTable.setShowHorizontalLines(true);
        scrollTablePanel.setViewportView(tasksTable);

        javax.swing.GroupLayout taskItemsLayout = new javax.swing.GroupLayout(taskItems);
        taskItems.setLayout(taskItemsLayout);
        taskItemsLayout.setHorizontalGroup(
            taskItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTablePanel)
        );
        taskItemsLayout.setVerticalGroup(
            taskItemsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollTablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainBodyLayout = new javax.swing.GroupLayout(mainBody);
        mainBody.setLayout(mainBodyLayout);
        mainBodyLayout.setHorizontalGroup(
            mainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(projectItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taskItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        mainBodyLayout.setVerticalGroup(
            mainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainBodyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(mainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(projects, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tasks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainBodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(taskItems, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout toolBarLayout = new javax.swing.GroupLayout(toolBar);
        toolBar.setLayout(toolBarLayout);
        toolBarLayout.setHorizontalGroup(
            toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toolBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mainBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolBarTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toolBarSubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        toolBarLayout.setVerticalGroup(
            toolBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toolBarLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(toolBarTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(toolBarSubtitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainBody, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(toolBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void projectIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projectIconMouseClicked
        // TODO add your handling code here:
        CriarProjeto criarProjeto = new CriarProjeto(this, rootPaneCheckingEnabled);
        criarProjeto.setVisible(true);
    }//GEN-LAST:event_projectIconMouseClicked

    private void taskIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_taskIconMouseClicked
        // TODO add your handling code here:
        CriarTarefa criarTarefa = new CriarTarefa(this, rootPaneCheckingEnabled);
        criarTarefa.setVisible(true);
    }//GEN-LAST:event_taskIconMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel mainBody;
    private javax.swing.JLabel projectIcon;
    private javax.swing.JPanel projectItems;
    private javax.swing.JList<String> projectList;
    private javax.swing.JLabel projectTitle;
    private javax.swing.JPanel projects;
    private javax.swing.JScrollPane scrollProjectPanel;
    private javax.swing.JScrollPane scrollTablePanel;
    private javax.swing.JLabel taskDefaultIcon;
    private javax.swing.JLabel taskDefaultSubtitle;
    private javax.swing.JLabel taskDefaultTitle;
    private javax.swing.JPanel taskEmpty;
    private javax.swing.JLabel taskEmptyIcon;
    private javax.swing.JPanel taskEmptyPanel;
    private javax.swing.JLabel taskEmptySubtitle;
    private javax.swing.JLabel taskEmptyTitle;
    private javax.swing.JLabel taskIcon;
    private javax.swing.JPanel taskItems;
    private javax.swing.JLabel taskTitle;
    private javax.swing.JPanel tasks;
    private javax.swing.JTable tasksTable;
    private javax.swing.JPanel toolBar;
    private javax.swing.JLabel toolBarSubtitle;
    private javax.swing.JLabel toolBarTitle;
    // End of variables declaration//GEN-END:variables
    
    public void decorateTableTasks(){
        tasksTable.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 16));
        tasksTable.getTableHeader().setBackground(new Color(0,153,102));
        tasksTable.getTableHeader().setForeground(new Color(255, 255, 255));
        tasksTable.setAutoCreateRowSorter(true);
    }
}
